---
- name: Run backend container
  docker_container:
    name: yolo-backend
    image: namayiana/yolo-backend:v1.0.1  
    ports:
      - 5000:5000
    tty: true
    env
      DB_HOST=mongodatabase
       DB_USER=admin
       DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    state: started

- name: Add backend to the network
  docker_network:
      - name: mongo_net
        connected:
          - yolo-backend
        appends: true