---
- name: Run backend container
  docker_container:
    name: yolo-backend
    image: namayiana/yolo-backend:v1.0.1  
    ports:
      - 5000:3000
    tty: true
    volumes:
      - mongodb:/data/db
    state: started

- name: Add client to the network
  docker_network:
      - name: mongo_net
        connected:
          - yolo-frontend
        appends: true