 
 version: '3.1'

 services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo_net
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_net
  
  backend:
    image: namayiana/yolo-backend:v1.0.1
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    networks:
      - mongo_net
    

  frontend:
    image: namayiana/yolo-frontend:v1.
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    networks:
      - mongo_net