---
- hosts: all
  become: True

  pre_tasks:
   - name: Update apt cache if needed.
     apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Import the public key used by the package management system
      gpg_key: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add - state=present
    - name: Add MongoDB repository
      apt_repository: repo='deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse' state=present

    - name: install mongodb
      apt: pkg=mongodb-org state=latest update_cache=yes
      notify:
      - start mongodb
  handlers:
    - name: start mongodb
      service: name=mongod state=started

    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes

    - name: GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: adding users to group docker
      user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop:
        - user1
        - user2

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'


