---
- hosts: all
  become: True

  pre_tasks:
   - name: Update apt cache if needed.
     apt: update_cache=yes cache_valid_time=3600

  tasks:
    

    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes

    - name: GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: adding users to group docker
      user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop:
        - user1
        - user2

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present

    - name: repository mongo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        state: present
        update_cache: yes

    - name: MongoDB - Install MongoDB
      apt:
      name: mongodb-org
      state: present
      update_cache: yes

    - name: MongoDB - Running state
  service:
    name: mongod
    state: started

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

      roles:
        - nodejs
      


