---
- hosts: all
  become: True
  vars: 
    mongo_image: mongo
    Node_version: "16"
    frontend_image: namayiana/yolo-frontend:v1.0.0
    backend_image: namayiana/yolo-backend:v1.0.0 
   
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600


  roles: 
    - all

- name: Pull image of mongo and launch container
  hosts: all
  become: true
  tags: mongo
  roles:
    - mongo

- name: Pull image of the backend and launch container
  hosts: all
  become: true
  tags: backend
  roles:
    - backend
  
- name: Pull image of the frontend and launch container
  hosts: all
  become: true
  tags: client
  roles:
    - client

    
    
     
      


