
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: node-deployment
            spec:
              # A deployment's specification:
              
              # 1. How many copies of each pod do we want?
              replicas: 3
            
              # 2. How do want to update the pods?
              strategy: 
                type: rollingUpdate
                rollingUpdate: 
                  maxSurge: 0
                  maxUnavailable: 20%
            
              # 3. Which pods are managed by this deployment?
              selector:
                # This must match the labels we set on the pod!
                matchLabels:
                  deploy: yolo
              
              # This template field is a regular pod configuration 
              # nested inside the deployment spec
              template:
                metadata:
                  # Set labels on the pod.
                  # This is used in the deployment selector.
                  labels:
                    deploy: yolo
                spec:
                  containers:
                    - image: namayiana/yolo-backend:v1.0.0
                      name: node-deployment
                      ports:
                       - containerPort: 5000
                         name: http
                         protocol: TCP