---
- name: Data volume creation
  docker_volume: 
    name: mongo_volume
    state: present 
    
- name: Start Mongo container
    docker_container:
      name: mongodatabase
      image: mongo
      ports: 
        -27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: yolomy
      volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_net
  