---
- name: Run frontend container
  docker_container:
    name: yolo-frontend
    image:     
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    networks:
      - mongo_net