---
- name: Run frontend container
  
    image: yolo-frontend
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    networks:
      - mongo_net