---
- name: Run frontend container
  docker_container:
    name: yolo-frontend
    image:     
    ports:
      - 3000:3000
    tty: true
     environment:
      DB_HOST=mongodatabase
      DB_USER=admin
      DB_PASSWORD=password
    volumes:
      - mongodb:/data/db
    state: started

- name: Add client to the network
  docker_network:
      - name: mongo_net
        connected:
          - yolo-frontend
        appends: true