apiVersion: v1

kind: Service

metadata:
   name: node-service
   labels:
     app: node-service
      
spec:
   type: LoadBalancer
   selector:
      app: yolo-pod
   ports:
     - protocol: TCP
       port: 5000
       targetPort: 5000